In [1]:
import pandas as pd
import numpy as np

In [2]:
sales = pd.read_csv("da_sales_transactions.csv")
customers = pd.read_csv("da_customer_data.csv")
products = pd.read_csv("da_product_catalogue.csv")

In [3]:
print("Sales:", sales.shape)
print("Customers:", customers.shape)
print("Products:", products.shape)

Sales: (1000, 11)
Customers: (200, 10)
Products: (50, 7)

In [4]:
sales.head()

,Transaction_ID,Date,Customer_ID,Product_ID,Category,Units,Unit_Price,Discount_Pct,Channel,City,Return_Flag
0,T1,2025-01-24,C2,P2,Sports,5,539,15,Marketplace,Pune,1
1,T2,2025-12-15,C3,P3,Grocery,1,4228,5,Marketplace,Delhi,0
2,T3,2025-10-11,C4,P4,Books,2,2061,15,Offline,Chennai,0
3,T4,2025-04-24,C5,P5,Electronics,3,2164,0,Website,Chennai,0
4,T5,2025-06-25,C6,P6,Apparel,1,2341,0,Website,Kolkata,0

In [5]:
customers.head()

,Customer_ID,City,Age_Band,Gender,Acquisition_Channel,First_Purchase_Date,Total_Orders,Total_Revenue,Last_Purchase_Date,Churned
0,C1,Delhi,18-24,F,Marketplace,2025-11-08,19,33219,2026-04-27,0
1,C2,Mumbai,18-24,M,App,2025-03-19,4,7139,2025-11-11,0
2,C3,Hyderabad,18-24,F,Marketplace,2025-04-03,3,10843,2025-12-22,0
3,C4,Pune,45-54,M,Marketplace,2024-09-13,17,44332,2026-06-01,0
4,C5,Pune,45-54,F,Offline,2024-11-27,7,36395,2026-04-11,0

In [6]:
products.head()

,Product_ID,Name,Category,MRP,COGS,Stock_Units,Avg_Monthly_Sales
0,P1,Product_1,Beauty,4921,2017,383,112
1,P2,Product_2,Home,3191,957,234,143
2,P3,Product_3,Electronics,2561,768,121,24
3,P4,Product_4,Apparel,3242,1069,490,184
4,P5,Product_5,Apparel,1119,369,388,27

In [7]:
print("Sales missing values:")
print(sales.isnull().sum())

print("\nCustomer missing values:")
print(customers.isnull().sum())

print("\nProduct missing values:")
print(products.isnull().sum())

Sales missing values:
Transaction_ID    0
Date              0
Customer_ID       0
Product_ID        0
Category          0
Units             0
Unit_Price        0
Discount_Pct      0
Channel           0
City              0
Return_Flag       0
dtype: int64

Customer missing values:
Customer_ID            0
City                   0
Age_Band               0
Gender                 0
Acquisition_Channel    0
First_Purchase_Date    0
Total_Orders           0
Total_Revenue          0
Last_Purchase_Date     0
Churned                0
dtype: int64

Product missing values:
Product_ID           0
Name                 0
Category             0
MRP                  0
COGS                 0
Stock_Units          0
Avg_Monthly_Sales    0
dtype: int64

In [8]:
print("Sales duplicates:", sales.duplicated().sum())
print("Customer duplicates:", customers.duplicated().sum())
print("Product duplicates:", products.duplicated().sum())

Sales duplicates: 0
Customer duplicates: 0
Product duplicates: 0

In [9]:
print("===== SALES DATA =====")
sales.info()
print("\nSales Statistical Summary:")
display(sales.describe())

print("\n===== CUSTOMER DATA =====")
customers.info()
print("\nCustomer Statistical Summary:")
display(customers.describe())

print("\n===== PRODUCT DATA =====")
products.info()
print("\nProduct Statistical Summary:")
display(products.describe())

===== SALES DATA =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  1000 non-null   object
 1   Date            1000 non-null   object
 2   Customer_ID     1000 non-null   object
 3   Product_ID      1000 non-null   object
 4   Category        1000 non-null   object
 5   Units           1000 non-null   int64
 6   Unit_Price      1000 non-null   int64
 7   Discount_Pct    1000 non-null   int64
 8   Channel         1000 non-null   object
 9   City            1000 non-null   object
 10  Return_Flag     1000 non-null   int64
dtypes: int64(4), object(7)
memory usage: 86.1+ KB

Sales Statistical Summary:

             Units   Unit_Price  Discount_Pct  Return_Flag
count  1000.000000  1000.000000   1000.000000  1000.000000
mean      3.098000  2745.834000      5.110000     0.097000
std       1.415768  1309.685271      5.798407     0.296106
min       1.000000   506.000000      0.000000     0.000000
25%       2.000000  1620.000000      0.000000     0.000000
50%       3.000000  2701.500000      5.000000     0.000000
75%       4.000000  3846.500000     10.000000     0.000000
max       5.000000  4996.000000     15.000000     1.000000

===== CUSTOMER DATA =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Customer_ID          200 non-null    object
 1   City                 200 non-null    object
 2   Age_Band             200 non-null    object
 3   Gender               200 non-null    object
 4   Acquisition_Channel  200 non-null    object
 5   First_Purchase_Date  200 non-null    object
 6   Total_Orders         200 non-null    int64
 7   Total_Revenue        200 non-null    int64
 8   Last_Purchase_Date   200 non-null    object
 9   Churned              200 non-null    int64
dtypes: int64(3), object(7)
memory usage: 15.8+ KB

Customer Statistical Summary:

       Total_Orders  Total_Revenue     Churned
count    200.000000     200.000000  200.000000
mean      11.535000   24963.105000    0.030000
std        5.806665   14546.944028    0.171015
min        1.000000     573.000000    0.000000
25%        7.000000   12449.000000    0.000000
50%       13.000000   22981.000000    0.000000
75%       17.000000   37768.000000    0.000000
max       20.000000   49920.000000    1.000000

===== PRODUCT DATA =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Product_ID         50 non-null     object
 1   Name               50 non-null     object
 2   Category           50 non-null     object
 3   MRP                50 non-null     int64
 4   COGS               50 non-null     int64
 5   Stock_Units        50 non-null     int64
 6   Avg_Monthly_Sales  50 non-null     int64
dtypes: int64(4), object(3)
memory usage: 2.9+ KB

Product Statistical Summary:

             MRP        COGS  Stock_Units  Avg_Monthly_Sales
count    50.0000    50.00000    50.000000          50.000000
mean   2262.9400   939.08000   277.140000         105.520000
std    1462.9008   638.30323   137.034482          61.198653
min     133.0000    45.00000     8.000000           8.000000
25%    1040.5000   436.00000   163.250000          49.500000
50%    2223.5000   784.00000   287.000000         111.500000
75%    3356.0000  1258.75000   394.000000         145.500000
max    4992.0000  2329.00000   498.000000         199.000000

In [10]:
sales["Gross_Sales"] = sales["Units"] * sales["Unit_Price"]

sales["Discount_Amount"] = (
    sales["Gross_Sales"] * sales["Discount_Pct"] / 100
)

sales["Net_Sales"] = (
    sales["Gross_Sales"] - sales["Discount_Amount"]
)

sales.head()

,Transaction_ID,Date,Customer_ID,Product_ID,Category,Units,Unit_Price,Discount_Pct,Channel,City,Return_Flag,Gross_Sales,Discount_Amount,Net_Sales
0,T1,2025-01-24,C2,P2,Sports,5,539,15,Marketplace,Pune,1,2695,404.25,2290.75
1,T2,2025-12-15,C3,P3,Grocery,1,4228,5,Marketplace,Delhi,0,4228,211.40,4016.60
2,T3,2025-10-11,C4,P4,Books,2,2061,15,Offline,Chennai,0,4122,618.30,3503.70
3,T4,2025-04-24,C5,P5,Electronics,3,2164,0,Website,Chennai,0,6492,0.00,6492.00
4,T5,2025-06-25,C6,P6,Apparel,1,2341,0,Website,Kolkata,0,2341,0.00,2341.00

In [11]:
print("Total Transactions:", len(sales))
print("Total Units Sold:", sales["Units"].sum())
print("Gross Sales:", sales["Gross_Sales"].sum())
print("Net Sales:", sales["Net_Sales"].sum())
print("Average Transaction Value:", sales["Net_Sales"].mean())
print("Average Discount:", sales["Discount_Pct"].mean())
print("Return Rate:", sales["Return_Flag"].mean() * 100)

Total Transactions: 1000
Total Units Sold: 3098
Gross Sales: 8456050
Net Sales: 8021851.199999999
Average Transaction Value: 8021.851199999999
Average Discount: 5.11
Return Rate: 9.700000000000001

In [12]:
churn_rate = customers["Churned"].mean() * 100

print("Customer Churn Rate:", churn_rate)

Customer Churn Rate: 3.0

In [13]:
channel_sales = sales.groupby("Channel").agg(
    Transactions=("Transaction_ID", "count"),
    Net_Sales=("Net_Sales", "sum"),
    Return_Rate=("Return_Flag", "mean")
).reset_index()

channel_sales["Return_Rate"] = channel_sales["Return_Rate"] * 100

channel_sales

       Channel  Transactions   Net_Sales  Return_Rate
0          App           250  1860232.85    10.800000
1  Marketplace           255  1961555.35     6.666667
2      Offline           246  2052421.60    10.162602
3      Website           249  2147641.40    11.244980

In [14]:
category_sales = sales.groupby("Category").agg(
    Transactions=("Transaction_ID", "count"),
    Units=("Units", "sum"),
    Net_Sales=("Net_Sales", "sum"),
    Return_Rate=("Return_Flag", "mean")
).reset_index()

category_sales["Return_Rate"] = category_sales["Return_Rate"] * 100

category_sales.sort_values("Net_Sales", ascending=False)

      Category  Transactions  Units   Net_Sales  Return_Rate
0      Apparel           152    468  1199522.90     8.552632
7       Sports           143    456  1088806.35     9.790210
1       Beauty           128    402  1037830.75    10.156250
6         Home           113    361  1001012.90     9.734513
2        Books           124    367   970256.55     8.870968
3  Electronics           113    344   953494.00     9.734513
5       Health           125    373   943798.30     8.000000
4      Grocery           102    327   827129.45    13.725490

In [15]:
analysis_df = sales.merge(
    customers,
    on="Customer_ID",
    how="left"
)

analysis_df = analysis_df.merge(
    products,
    on="Product_ID",
    how="left"
)

analysis_df.head()

,Transaction_ID,Date,Customer_ID,Product_ID,Category_x,Units,Unit_Price,Discount_Pct,Channel,City_x,...,Total_Orders,Total_Revenue,Last_Purchase_Date,Churned,Name,Category_y,MRP,COGS,Stock_Units,Avg_Monthly_Sales
0,T1,2025-01-24,C2,P2,Sports,5,539,15,Marketplace,Pune,...,4,7139,2025-11-11,0,Product_2,Home,3191,957,234,143
1,T2,2025-12-15,C3,P3,Grocery,1,4228,5,Marketplace,Delhi,...,3,10843,2025-12-22,0,Product_3,Electronics,2561,768,121,24
2,T3,2025-10-11,C4,P4,Books,2,2061,15,Offline,Chennai,...,17,44332,2026-06-01,0,Product_4,Apparel,3242,1069,490,184
3,T4,2025-04-24,C5,P5,Electronics,3,2164,0,Website,Chennai,...,7,36395,2026-04-11,0,Product_5,Apparel,1119,369,388,27
4,T5,2025-06-25,C6,P6,Apparel,1,2341,0,Website,Kolkata,...,15,25969,2025-10-23,0,Product_6,Electronics,1835,550,8,167

In [16]:
print("Combined dataset shape:", analysis_df.shape)

Combined dataset shape: (1000, 29)

In [17]:
print(
    "Customer match rate:",
    sales["Customer_ID"].isin(customers["Customer_ID"]).mean() * 100
)

print(
    "Product match rate:",
    sales["Product_ID"].isin(products["Product_ID"]).mean() * 100
)

Customer match rate: 100.0
Product match rate: 100.0

In [18]:
analysis_df.to_csv(
    "cleaned_sales_customer_product.csv",
    index=False
)

print("Cleaned dataset exported successfully.")

Cleaned dataset exported successfully.

In [19]:
import os

print(
    "File exists:",
    os.path.exists("cleaned_sales_customer_product.csv")
)

File exists: True